matrix:
  include:
    # Check if latex files are correct
    - language: minimal
      dist: xenial
      sudo: true
      before_install:
       - sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-extra-utils poppler-utils
       - cd ./documentation/diagrams
      script:
       - chmod +x ./creatediagrams.sh
       - ./creatediagrams.sh
