name: Component Tests

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install pytest and run tests
      run: |
        sudo pip install pytest pytest-html &&
        cd ./ContinuousIntegration &&
        chmod +x ./run_component_tests.sh && ./run_component_tests.sh
    
    - name: Archive component test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Report for BusinessLogic
        path: Test/ComponentTest/BusinessLogic_Test_Report.html
